### ISSUE TITLE
Readme - Ubuntu version confusion

### ISSUE THREAD

**Issue by Wachobc** [jasoneckert/CengageLinux#1]
Hello,
Setting up my Spring 2024 course using the 6th edition of the book.
Came here to learn about changes to the assignments with regards to the Linux versions.
I'm having trouble finding Ubuntu Server 23.04.  
I am not finding 23.04 on the Ubuntu website.
What am I missing?
Thank you,

**Comment by jasoneckert** [comment]
That's a typo on my part - 22.04 is the latest LTS you'll find on https://ubuntu.com/download/server and the one the book was originally written to match.  However, I tested the labs on both 23.04 (https://releases.ubuntu.com/lunar/) and more recently on 23.10 (also at https://ubuntu.com/download/server), but I forgot to update the version number from 23.04 to  23.10, so I fixed that just now.
